apiVersion: apps/v1
kind: Deployment
metadata:
  name: to-do-list
spec:
  selector:
    matchLabels:
      app: to-do-list
  template:
    metadata:
      labels: 
        app: to-do-list
    spec:
      containers:
      - name: container-crud
        image: crisvagner/to-do-list:v1
        ports: 
        - containerPort: 3000

---

apiVersion: v1
kind: Service
metadata:
  name: to-do-list
spec: 
  selector:
    app: to-do-list
  ports:
    - port: 70
      targetPort: 3000
      nodePort: 30000
  type: NodePort
